NOISSUE - Update logger to slog
absmach/agent pull request #5
Opened 2024-01-31 13:08 UTC by ianmuchyri

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Update the logger used from using the Magistrala logger which no longer exists to using the slog internal go package
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
NOISSUE
### List any changes that modify/break current functionality
NONE
### Have you included tests for your changes?
NO
### Did you document any new/modified functionality?
NO
### Notes

2024-01-31 13:32 UTC, rodneyosodo requested changes

2024-01-31 13:32 UTC, rodneyosodo commented on pkg/conn/conn.go
>  		b.logger.Info(fmt.Sprintf("Control command for uuid %s and command string %s", uuid, cmdStr))
Also update this

2024-01-31 13:32 UTC, rodneyosodo commented on pkg/conn/conn.go
>  		b.logger.Info(fmt.Sprintf("Execute command for uuid %s and command string %s", uuid, cmdStr))
an this

2024-01-31 13:32 UTC, rodneyosodo commented on pkg/bootstrap/bootstrap.go
>  		logger.Debug(fmt.Sprintf("Retries remaining: %d. Retrying in %d seconds", retries, retryDelaySec))
Update log messages include key-value pairs

2024-01-31 13:32 UTC, rodneyosodo commented on cmd/main.go
> +		log.Fatal(fmt.Sprintf("Failed to connect to Broker: %s %s", err, cfg.Server.BrokerURL))
Add error and url as KV pairs

2024-02-01 08:09 UTC, rodneyosodo requested changes

2024-02-01 08:09 UTC, rodneyosodo commented on pkg/agent/api/logging.go
> +		lm.logger.Info("AddConfig completed successfully.", duration)
```suggestion
		lm.logger.Info("Add config completed successfully.", duration)
```

2024-02-01 08:09 UTC, rodneyosodo commented on pkg/agent/api/logging.go
> +		lm.logger.Info("Config completed successfully.", slog.String("duration", time.Since(begin).String()))
```suggestion
		lm.logger.Info("Retrieve config  completed successfully.", slog.String("duration", time.Since(begin).String()))
```

Look at what the functions are doing then log the correct message

2024-02-01 09:27 UTC, dborovcanin requested changes

2024-02-01 09:27 UTC, dborovcanin commented on cmd/main.go
> +		log.Fatalf(err.Error())
Keep the previous version.

2024-02-01 09:27 UTC, dborovcanin commented on cmd/main.go
> +		return &slog.Logger{}, fmt.Errorf(`{"level":"error","message":"%s: %s","ts":"%s"}`, err, levelText, time.RFC3339Nano)
Fix the error by using the actual timestamp instead of the timestamp layout.

2024-02-01 09:27 UTC, dborovcanin commented on pkg/agent/api/logging.go
> +		lm.logger.Info("Config completed successfully.", slog.String("duration", time.Since(begin).String()))
This has been changed recently in Magistrala to provide more human-friendly logs.

2024-02-01 11:37 UTC, dborovcanin approved these changes

2024-02-01 22:41 UTC, rodneyosodo approved these changes

2024-02-02 07:56 UTC, merged